name: Deploy
on:
  push:
    branches:
      - main
      - release/*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install vsce
        run: npm install -g vsce
      - name: Package VSCode Extension
        run: vsce package --out extension.vsix
      - name: Publish VSCode Extension
        uses: HaaLeo/publish-vscode-extension@v0.6.0
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          vsixFile: extension.vsix
